# image: alpine:latest
stages: 
  - tests
  - deploy

Testing:
  stage: tests
  tags:
  - payment, ubuntu, wordpress-server
  script:
  # - ./vendor/bin/phpunit
  - echo whoami
  - composer install
  - /vendor/bin/phpunit

Deploy:
  stage: deploy
  tags:
  - payment, ubuntu, wordpress-server
  before_script:
  - 'command -v ssh-agent >/dev/null || ( apk add --update openssh )' 
  - eval $(ssh-agent -s)
  - echo "$SSH_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan -t rsa $IP >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  script:
  - ssh $USER@$IP "hostname && echo 'Welcome!!!' > welcome.txt"
  # artifacts:
  #   paths:
  #   - public
  only:
  - master